// Code generated by tools/cmd/traficom-gen-go. DO NOT EDIT.
// Source: data/traficom/traficom.csv

package vin

import (
	vinv1 "github.com/way-platform/vin-go/proto/gen/go/wayplatform/connect/vin/v1"
)

// traficomData contains fuel tank and battery capacity data for known vehicle models.
// Data sourced from Finnish Traficom vehicle registry analysis cross-referenced with
// OEM spec sheets (ultimatespecs.com, toyota.fi, Wikipedia for EVs).
var traficomData = []traficomConfig{
	{Key: 0x0000000100050001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 70, BatteryCapacityKwh: 0}},
	{Key: 0x00000001000d0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 75, BatteryCapacityKwh: 0}},
	{Key: 0x00000001000d0002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 35.8}},
	{Key: 0x00000001004b0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 50, BatteryCapacityKwh: 0}},
	{Key: 0x00000001007e0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 80, BatteryCapacityKwh: 0}},
	{Key: 0x0000000a000d0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 75, BatteryCapacityKwh: 0}},
	{Key: 0x0000000a00820001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 75, BatteryCapacityKwh: 0}},
	{Key: 0x0000000b000c0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 60, BatteryCapacityKwh: 0}},
	{Key: 0x0000000b000c0002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 50}},
	{Key: 0x0000000b004c0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 69, BatteryCapacityKwh: 0}},
	{Key: 0x0000000b004c0002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 75}},
	{Key: 0x0000000b00540001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 90, BatteryCapacityKwh: 0}},
	{Key: 0x0000000c00480001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 90, BatteryCapacityKwh: 0}},
	{Key: 0x0000000c00480002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 75}},
	{Key: 0x0000000c00490001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 50, BatteryCapacityKwh: 0}},
	{Key: 0x0000000e000b0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 60, BatteryCapacityKwh: 0}},
	{Key: 0x0000000e000b0002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 50}},
	{Key: 0x0000000e00520001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 69, BatteryCapacityKwh: 0}},
	{Key: 0x0000000e00520002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 75}},
	{Key: 0x0000000e00560001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 90, BatteryCapacityKwh: 0}},
	{Key: 0x0000000f00530001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 90, BatteryCapacityKwh: 0}},
	{Key: 0x0000000f00530002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 79}},
	{Key: 0x0000001800090001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 80, BatteryCapacityKwh: 0}},
	{Key: 0x0000001800090002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 52}},
	{Key: 0x00000018000a0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 80, BatteryCapacityKwh: 0}},
	{Key: 0x0000001800510001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 60, BatteryCapacityKwh: 0}},
	{Key: 0x0000001800510002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 44}},
	{Key: 0x0000001d004a0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 80, BatteryCapacityKwh: 0}},
	{Key: 0x0000001d00570001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 69, BatteryCapacityKwh: 0}},
	{Key: 0x0000001d00570002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 75}},
	{Key: 0x0000001d007b0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 53, BatteryCapacityKwh: 0}},
	{Key: 0x0000001d007b0002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 50}},
	{Key: 0x0000002100010001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 57, BatteryCapacityKwh: 0}},
	{Key: 0x0000002100010002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 60}},
	{Key: 0x0000002100020001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 70, BatteryCapacityKwh: 0}},
	{Key: 0x0000002100020002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 113}},
	{Key: 0x0000002100030002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 113}},
	{Key: 0x0000002100690001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 54, BatteryCapacityKwh: 0}},
	{Key: 0x0000002200060001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 70, BatteryCapacityKwh: 0}},
	{Key: 0x00000022002c0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 56, BatteryCapacityKwh: 0}},
	{Key: 0x0000002200460001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 70, BatteryCapacityKwh: 0}},
	{Key: 0x0000002200460002, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_ELECTRIC, FuelTankCapacityL: 0, BatteryCapacityKwh: 64}},
	{Key: 0x0000002200460004, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_GASOLINE, FuelTankCapacityL: 54, BatteryCapacityKwh: 13.6}},
	{Key: 0x0000002200470001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 80, BatteryCapacityKwh: 0}},
	{Key: 0x0000002200730001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 48, BatteryCapacityKwh: 0}},
	{Key: 0x00000052004f0001, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_DIESEL, FuelTankCapacityL: 76, BatteryCapacityKwh: 0}},
}
