package vin

import (
	"slices"

	"github.com/way-platform/vin-go/internal/wmi"
	vinv1 "github.com/way-platform/vin-go/proto/gen/go/wayplatform/connect/vin/v1"
)

// wmiEntry represents a WMI1 entry in the lookup table
type wmiEntry struct {
	Key        uint16 // base36(WMI1)
	WMI        *wmiRecord
	LVMEntries []lvmEntry // Only populated if WMI1 third char is '9'
}

// lvmEntry represents a Low Volume Manufacturer entry (WMI2)
type lvmEntry struct {
	Key uint16 // base36(WMI2)
	WMI *wmiRecord
}

// wmiRecord contains the manufacturer information for a WMI entry
type wmiRecord struct {
	M   string
	C   vinv1.Country
	R   vinv1.Region
	B   vinv1.Brand
	Cat vinv1.Category
}

// lookup is the generated sorted slice of WMI entries
// This is generated by the code generator from data/wmi.csv in wmi_data.go

// Lookup performs a binary search lookup for a WMI entry.
// wmi1 is the 3-character WMI code (positions 1-3).
// wmi2 is optional and used for Low Volume Manufacturers (positions 12-14 when WMI1 third char is '9').
// Returns nil if not found.
func Lookup(wmi1, wmi2 string) *wmiRecord {
	if len(wmi1) != 3 {
		return nil
	}

	// Convert WMI1 to base36
	key, ok := wmi.ToBase36(wmi1)
	if !ok {
		return nil
	}

	// Binary search for WMI1
	idx, found := slices.BinarySearchFunc(lookup, key, func(e wmiEntry, k uint16) int {
		return int(e.Key) - int(k)
	})

	if !found {
		return nil
	}

	entry := lookup[idx]

	// Check if this is an LVM (Low Volume Manufacturer) - third char is '9'
	if len(wmi1) >= 3 && wmi1[2] == '9' && wmi2 != "" {
		if len(wmi2) != 3 {
			return entry.WMI
		}

		// Convert WMI2 to base36
		wmi2Key, ok := wmi.ToBase36(wmi2)
		if !ok {
			return entry.WMI
		}

		// Binary search for WMI2 in LVM entries
		lvmIdx, lvmFound := slices.BinarySearchFunc(entry.LVMEntries, wmi2Key, func(e lvmEntry, k uint16) int {
			return int(e.Key) - int(k)
		})

		if lvmFound {
			return entry.LVMEntries[lvmIdx].WMI
		}
	}

	return entry.WMI
}
