package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/way-platform/vin-go/internal/codegen"
	vinv1 "github.com/way-platform/vin-go/proto/gen/go/wayplatform/connect/vin/v1"
)

type entry struct {
	Key      uint64
	FuelType int32
	FuelTankCapacityL    float64
	BatteryCapacityKwh  float64
}

func main() {
	inputFile := flag.String("input", "data/traficom/traficom.csv", "Path to the Traficom CSV file")
	outputFile := flag.String("output", "traficom.gen.go", "Path to the output Go file")
	packageName := flag.String("package", "vin", "Package name for generated Go code")
	flag.Parse()

	if err := run(*inputFile, *outputFile, *packageName); err != nil {
		log.Fatalf("failed to run: %v", err)
	}
}

func run(inputFile, outputFile, packageName string) error {
	entries, err := readCSV(inputFile)
	if err != nil {
		return fmt.Errorf("reading CSV: %w", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Key < entries[j].Key
	})

	g := codegen.NewFile(outputFile, "github.com/way-platform/vin-go")
	g.P("// Code generated by tools/cmd/traficom-gen-go. DO NOT EDIT.")
	g.P("// Source: data/traficom/traficom.csv")
	g.P("")
	g.P("package ", packageName)
	g.P("")
	g.P("import (")
	g.P("\tvinv1 \"github.com/way-platform/vin-go/proto/gen/go/wayplatform/connect/vin/v1\"")
	g.P(")")
	g.P("")
	g.P("// traficomData contains fuel tank and battery capacity data for known vehicle models.")
	g.P("// Data sourced from Finnish Traficom vehicle registry analysis cross-referenced with")
	g.P("// OEM spec sheets (ultimatespecs.com, toyota.fi, Wikipedia for EVs).")
	g.P("var traficomData = []traficomConfig{")
	for _, e := range entries {
		ftName := vinv1.FuelType_name[e.FuelType]
		g.P(fmt.Sprintf("\t{Key: 0x%016x, traficomEnergySpec: traficomEnergySpec{FuelType: vinv1.FuelType_%s, FuelTankCapacityL: %s, BatteryCapacityKwh: %s}},", e.Key, ftName, formatFloat(e.FuelTankCapacityL), formatFloat(e.BatteryCapacityKwh)))
	}
	g.P("}")

	content, err := g.Content()
	if err != nil {
		return fmt.Errorf("generating content: %w", err)
	}

	if err := os.WriteFile(outputFile, content, 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	fmt.Printf("Generated %s with %d entries\n", outputFile, len(entries))
	return nil
}

func readCSV(path string) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	reader := csv.NewReader(f)
	records, err := reader.ReadAll()
	if err != nil {
		return nil, err
	}

	if len(records) < 2 {
		return nil, fmt.Errorf("CSV must have header + at least one data row")
	}

	var entries []entry
	for i, row := range records[1:] {
		if len(row) < 5 {
			return nil, fmt.Errorf("row %d: expected at least 5 columns, got %d", i+2, len(row))
		}

		brand := strings.TrimSpace(row[0])
		model := strings.TrimSpace(row[1])
		fuelType := strings.TrimSpace(row[2])
		tankStr := strings.TrimSpace(row[3])
		battStr := strings.TrimSpace(row[4])

		brandVal, ok := vinv1.Brand_value[brand]
		if !ok {
			return nil, fmt.Errorf("row %d: unknown brand %q", i+2, brand)
		}
		modelVal, ok := vinv1.Model_value[model]
		if !ok {
			return nil, fmt.Errorf("row %d: unknown model %q", i+2, model)
		}
		fuelTypeVal, ok := vinv1.FuelType_value[fuelType]
		if !ok {
			return nil, fmt.Errorf("row %d: unknown fuel_type %q", i+2, fuelType)
		}

		tankL, err := strconv.ParseFloat(tankStr, 64)
		if err != nil {
			return nil, fmt.Errorf("row %d: invalid fuel_tank_capacity_l %q: %w", i+2, tankStr, err)
		}
		battKWh, err := strconv.ParseFloat(battStr, 64)
		if err != nil {
			return nil, fmt.Errorf("row %d: invalid battery_capacity_kwh %q: %w", i+2, battStr, err)
		}

		// Key layout: brand<<32 | model<<16 | fuel_type
		key := uint64(brandVal)<<32 | uint64(modelVal)<<16 | uint64(fuelTypeVal)
		entries = append(entries, entry{Key: key, FuelType: fuelTypeVal, FuelTankCapacityL: tankL, BatteryCapacityKwh: battKWh})
	}

	return entries, nil
}

func formatFloat(f float64) string {
	if f == 0 {
		return "0"
	}
	return strconv.FormatFloat(f, 'f', -1, 64)
}
