package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/way-platform/vin-go/internal/codegen"
	vinv1 "github.com/way-platform/vin-go/proto/gen/go/wayplatform/connect/vin/v1"
)

func main() {
	csvFile := flag.String("csv", "data/wmi.csv", "Path to the WMI CSV file")
	outputFile := flag.String("output", "wmi_data.go", "Path to the output Go file")
	packageName := flag.String("package", "vin", "Package name for generated code")
	flag.Parse()

	if err := run(*csvFile, *outputFile, *packageName); err != nil {
		log.Fatalf("failed to run: %v", err)
	}
}

type CSVRecord struct {
	WMI1         string
	WMI1Base36   uint16
	WMI2         string
	WMI2Base36   uint16
	DataSource   string
	Manufacturer string
	Country      string
	Region       string
	Brand        string
}

func run(csvFile, outputFile, packageName string) error {
	// Read CSV
	records, err := readCSV(csvFile)
	if err != nil {
		return fmt.Errorf("reading CSV: %w", err)
	}

	// Group by WMI1
	entries := groupByWMI1(records)

	// Sort entries by WMI1 base36 key
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Key < entries[j].Key
	})

	// Generate Go code
	return generateGoCode(entries, outputFile, packageName)
}

func readCSV(filename string) ([]CSVRecord, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		return nil, err
	}

	if len(rows) == 0 {
		return nil, fmt.Errorf("empty CSV file")
	}

	// Skip header
	records := make([]CSVRecord, 0, len(rows)-1)
	for i := 1; i < len(rows); i++ {
		row := rows[i]
		if len(row) < 9 {
			continue
		}

		wmi1Base36, err := strconv.ParseUint(row[1], 10, 16)
		if err != nil {
			continue
		}

		var wmi2Base36 uint64
		if row[2] != "" {
			wmi2Base36, err = strconv.ParseUint(row[3], 10, 16)
			if err != nil {
				continue
			}
		}

		records = append(records, CSVRecord{
			WMI1:         row[0],
			WMI1Base36:   uint16(wmi1Base36),
			WMI2:         row[2],
			WMI2Base36:   uint16(wmi2Base36),
			DataSource:   row[4],
			Manufacturer: row[5],
			Country:      row[6],
			Region:       row[7],
			Brand:        row[8],
		})
	}

	return records, nil
}

type Entry struct {
	Key        uint16
	WMI        *WMIInfo
	LVMEntries []LVMEntry
}

type LVMEntry struct {
	Key uint16
	WMI *WMIInfo
}

type WMIInfo struct {
	Manufacturer string
	Country      vinv1.Country
	Region       vinv1.Region
	Brand        vinv1.Brand
}

func groupByWMI1(records []CSVRecord) []Entry {
	// Map to group by WMI1
	wmi1Map := make(map[uint16]*Entry)

	for _, record := range records {
		entry, exists := wmi1Map[record.WMI1Base36]
		if !exists {
			entry = &Entry{
				Key:        record.WMI1Base36,
				LVMEntries: nil, // Will be set to empty slice if needed
			}
			wmi1Map[record.WMI1Base36] = entry
		}

		// Convert enum strings to proto enum values
		country := convertCountry(record.Country)
		region := convertRegion(record.Region)
		brand := convertBrand(record.Brand)

		wmiInfo := &WMIInfo{
			Manufacturer: record.Manufacturer,
			Country:      country,
			Region:       region,
			Brand:        brand,
		}

		if record.WMI2 == "" {
			// Standard entry - set WMI if not already set
			if entry.WMI == nil {
				entry.WMI = wmiInfo
			}
		} else {
			// LVM entry - initialize slice if needed
			if entry.LVMEntries == nil {
				entry.LVMEntries = make([]LVMEntry, 0)
			}
			lvmEntry := LVMEntry{
				Key: record.WMI2Base36,
				WMI: wmiInfo,
			}
			entry.LVMEntries = append(entry.LVMEntries, lvmEntry)
			// If no standard WMI is set yet, use first LVM entry as default
			// This handles cases where WMI1 only has LVM entries
			if entry.WMI == nil {
				entry.WMI = wmiInfo
			}
		}
	}

	// Convert to slice and sort LVM entries
	entries := make([]Entry, 0, len(wmi1Map))
	for _, entry := range wmi1Map {
		// Sort LVM entries by key if they exist
		if entry.LVMEntries != nil {
			sort.Slice(entry.LVMEntries, func(i, j int) bool {
				return entry.LVMEntries[i].Key < entry.LVMEntries[j].Key
			})
		}
		entries = append(entries, *entry)
	}

	return entries
}

func generateGoCode(entries []Entry, outputFile, packageName string) error {
	f := codegen.NewFile(outputFile, "github.com/way-platform/vin-go")
	f.P("// Code generated by tools/cmd/wmi-gen-data. DO NOT EDIT.")
	f.P()
	f.P("package ", packageName)
	f.P()

	f.P("var lookup = []wmiEntry{")

	for _, entry := range entries {
		// Build wmiRecord fields string, skipping zero values
		var wmiFields []string
		wmiFields = append(wmiFields, "M: "+strconv.Quote(entry.WMI.Manufacturer))

		if entry.WMI.Country != vinv1.Country_COUNTRY_UNSPECIFIED {
			wmiFields = append(wmiFields, fmt.Sprintf("C: %d", int(entry.WMI.Country)))
		}

		if entry.WMI.Region != vinv1.Region_REGION_UNSPECIFIED {
			wmiFields = append(wmiFields, fmt.Sprintf("R: %d", int(entry.WMI.Region)))
		}

		if entry.WMI.Brand != vinv1.Brand_BRAND_UNSPECIFIED {
			wmiFields = append(wmiFields, fmt.Sprintf("B: %d", int(entry.WMI.Brand)))
		}

		wmiRecordStr := "&wmiRecord{" + strings.Join(wmiFields, ", ") + "}"

		// Build entry string
		entryParts := []string{fmt.Sprintf("Key: %d", entry.Key), "WMI: " + wmiRecordStr}

		// Add LVM entries if present
		if len(entry.LVMEntries) > 0 {
			f.P("\t{", strings.Join(entryParts, ", "), ", LVMEntries: []lvmEntry{")
			for _, lvm := range entry.LVMEntries {
				var lvmWmiFields []string
				lvmWmiFields = append(lvmWmiFields, "M: "+strconv.Quote(lvm.WMI.Manufacturer))

				if lvm.WMI.Country != vinv1.Country_COUNTRY_UNSPECIFIED {
					lvmWmiFields = append(lvmWmiFields, fmt.Sprintf("C: %d", int(lvm.WMI.Country)))
				}

				if lvm.WMI.Region != vinv1.Region_REGION_UNSPECIFIED {
					lvmWmiFields = append(lvmWmiFields, fmt.Sprintf("R: %d", int(lvm.WMI.Region)))
				}

				if lvm.WMI.Brand != vinv1.Brand_BRAND_UNSPECIFIED {
					lvmWmiFields = append(lvmWmiFields, fmt.Sprintf("B: %d", int(lvm.WMI.Brand)))
				}

				lvmWmiRecordStr := "&wmiRecord{" + strings.Join(lvmWmiFields, ", ") + "}"
				f.P("\t\t{Key: ", lvm.Key, ", WMI: ", lvmWmiRecordStr, "},")
			}
			f.P("\t}},")
		} else {
			f.P("\t{", strings.Join(entryParts, ", "), "},")
		}
	}

	f.P("}")

	content, err := f.Content()
	if err != nil {
		return fmt.Errorf("generating content: %w", err)
	}

	var output *os.File
	if outputFile == "-" {
		output = os.Stdout
	} else {
		output, err = os.Create(outputFile)
		if err != nil {
			return fmt.Errorf("creating output file: %w", err)
		}
		defer output.Close()
	}

	_, err = output.Write(content)
	return err
}

func convertCountry(s string) vinv1.Country {
	if s == "" {
		return vinv1.Country_COUNTRY_UNSPECIFIED
	}
	val, ok := vinv1.Country_value[s]
	if !ok {
		return vinv1.Country_COUNTRY_UNSPECIFIED
	}
	return vinv1.Country(val)
}

func convertRegion(s string) vinv1.Region {
	if s == "" {
		return vinv1.Region_REGION_UNSPECIFIED
	}
	val, ok := vinv1.Region_value[s]
	if !ok {
		return vinv1.Region_REGION_UNSPECIFIED
	}
	return vinv1.Region(val)
}

func convertBrand(s string) vinv1.Brand {
	if s == "" {
		return vinv1.Brand_BRAND_UNSPECIFIED
	}
	brandStr := strings.ToUpper(s)
	val, ok := vinv1.Brand_value[brandStr]
	if !ok {
		return vinv1.Brand_BRAND_UNSPECIFIED
	}
	return vinv1.Brand(val)
}
