edition = "2023";

package wayplatform.connect.vin.v1;

import "google/protobuf/descriptor.proto";
import "wayplatform/connect/vin/v1/conglomerate.proto";
import "wayplatform/connect/vin/v1/vpic.proto";

extend google.protobuf.EnumValueOptions {
  // The brand for the enum value.
  repeated Brand brand = 50349;
}

// A vehicle brand.
//
// Brand is the common trade name under which manufacturers offer their model series on the vehicle market.
// It usually corresponds to the lettering or emblem on the vehicle.
enum Brand {
  // Default value. This value is unused.
  BRAND_UNSPECIFIED = 0;

  // Volkswagen.
  VOLKSWAGEN = 1 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 482 // Volkswagen
  ];

  // Skoda.
  SKODA = 2 [(conglomerate) = VOLKSWAGEN_GROUP];

  // Audi.
  AUDI = 3 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 582 // Audi
  ];

  // Cupra.
  CUPRA = 4 [(conglomerate) = VOLKSWAGEN_GROUP];

  // Seat.
  SEAT = 5 [(conglomerate) = VOLKSWAGEN_GROUP];

  // Porsche.
  PORSCHE = 6 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 584 // Porsche
  ];

  // Bentley.
  BENTLEY = 7 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 583 // Bentley
  ];

  // Bugatti.
  BUGATTI = 8 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 454 // Bugatti
  ];

  // Lamborghini.
  LAMBORGHINI = 9 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 502 // Lamborghini
  ];

  // MAN.
  MAN = 10 [(conglomerate) = VOLKSWAGEN_GROUP];

  // Peugeot.
  PEUGEOT = 11 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 5554 // Peugeot
  ];

  // Opel.
  OPEL = 12 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 471 // Opel
  ];

  // Vauxhall.
  VAUXHALL = 13 [(conglomerate) = STELLANTIS];

  // Citroen.
  CITROEN = 14 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 12455 // Citroen
  ];

  // Fiat.
  FIAT = 15 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 492 // Fiat
  ];

  // Jeep.
  JEEP = 16 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 483 // Jeep
  ];

  // Alfa Romeo.
  ALFA_ROMEO = 17 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 493 // Alfa Romeo
  ];

  // DS.
  DS = 18 [(conglomerate) = STELLANTIS];

  // Lancia.
  LANCIA = 19 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 497 // Lancia.
  ];

  // Chrysler.
  CHRYSLER = 20 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 477 // Chrysler
  ];

  // Dodge.
  DODGE = 21 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 476 // Dodge
  ];

  // Maserati.
  MASERATI = 22 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 443 // Maserati
  ];

  // RAM.
  RAM = 23 [
    (conglomerate) = STELLANTIS,
    (vpic_make_id) = 496 // Ram
  ];

  // Renault.
  RENAULT = 24 [
    (conglomerate) = RENAULT_GROUP,
    (vpic_make_id) = 13647 // Renault
  ];

  // Dacia.
  DACIA = 25 [(conglomerate) = RENAULT_GROUP];

  // Alpine.
  ALPINE = 26 [
    (conglomerate) = RENAULT_GROUP,
    (vpic_make_id) = 11081 // Alpine
  ];

  // Hyundai.
  HYUNDAI = 27 [
    (conglomerate) = HYUNDAI_GROUP,
    (vpic_make_id) = 498 // Hyundai
  ];

  // Kia.
  KIA = 28 [
    (conglomerate) = HYUNDAI_GROUP,
    (vpic_make_id) = 499 // Kia
  ];

  // Toyota.
  TOYOTA = 29 [
    (conglomerate) = TOYOTA_GROUP,
    (vpic_make_id) = 448 // Toyota
  ];

  // Lexus.
  LEXUS = 30 [
    (conglomerate) = TOYOTA_GROUP,
    (vpic_make_id) = 515 // Lexus
  ];

  // BMW.
  BMW = 31 [
    (conglomerate) = BMW_GROUP,
    (vpic_make_id) = 452 // BMW
  ];

  // Mini.
  MINI = 32 [
    (conglomerate) = BMW_GROUP,
    (vpic_make_id) = 456 // MINI
  ];

  // Mercedes-Benz.
  MERCEDES_BENZ = 33 [
    (conglomerate) = MERCEDES_BENZ_GROUP,
    (vpic_make_id) = 449, // Mercedes-Benz
    (vpic_make_id) = 10285 // Daimler
  ];

  // Ford.
  FORD = 34 [
    (conglomerate) = FORD_MOTOR_COMPANY,
    (vpic_make_id) = 460 // Ford
  ];

  // Volvo Cars.
  VOLVO_CARS = 35 [
    (conglomerate) = ZHEJIANG_GEELY_HOLDING_GROUP,
    (vpic_make_id) = 485 // Volvo
  ];

  // Nissan.
  NISSAN = 36 [(vpic_make_id) = 478 /* Nissan */];

  // Tesla.
  TESLA = 37 [(vpic_make_id) = 441 /* Tesla */];

  // Suzuki.
  SUZUKI = 38 [(vpic_make_id) = 509 /* Suzuki */];

  // BYD.
  BYD = 39 [(vpic_make_id) = 1991 /* BYD */];

  // Mazda.
  MAZDA = 40 [(vpic_make_id) = 473 /* Mazda */];

  // Land Rover.
  LAND_ROVER = 41 [
    (conglomerate) = JAGUAR_LAND_ROVER_GROUP,
    (vpic_make_id) = 444 // Land Rover
  ];

  // Jaguar.
  JAGUAR = 42 [
    (conglomerate) = JAGUAR_LAND_ROVER_GROUP,
    (vpic_make_id) = 442 // Jaguar
  ];

  // Honda.
  HONDA = 43 [
    (conglomerate) = HONDA_MOTOR_COMPANY,
    (vpic_make_id) = 474 // Honda
  ];

  // Mitsubishi.
  MITSUBISHI = 44 [(vpic_make_id) = 481 /* Mitsubishi */];

  // Volvo Trucks.
  VOLVO_TRUCKS = 45 [
    (conglomerate) = VOLVO_GROUP,
    (vpic_make_id) = 487
  ];

  // Aston Martin.
  ASTON_MARTIN = 46 [(vpic_make_id) = 440 /* Aston Martin */];

  // Great Wall.
  GREAT_WALL = 47;

  // Iveco.
  IVECO = 48 [(vpic_make_id) = 5744 /* Iveco */];

  // Smart.
  SMART = 49 [
    (conglomerate) = MERCEDES_BENZ_GROUP,
    (conglomerate) = ZHEJIANG_GEELY_HOLDING_GROUP,
    (vpic_make_id) = 504 // smart
  ];

  // Chevrolet.
  CHEVROLET = 50 [
    (conglomerate) = GENERAL_MOTORS,
    (vpic_make_id) = 467 // Chevrolet
  ];

  // Subaru.
  SUBARU = 51 [(vpic_make_id) = 523 /* Subaru */];

  // SsangYong.
  SSANGYONG = 52 [(vpic_make_id) = 508];

  // Lada.
  LADA = 53;

  // Rolls-Royce.
  ROLLS_ROYCE = 54 [
    (conglomerate) = BMW_GROUP,
    (vpic_make_id) = 445 // Rolls-Royce
  ];

  // Buell.
  BUELL = 55 [(vpic_make_id) = 590 /* Buell */];

  // Freightliner.
  FREIGHTLINER = 56 [(vpic_make_id) = 450 /* Freightliner */];

  // Lincoln.
  LINCOLN = 57 [
    (conglomerate) = FORD_MOTOR_COMPANY,
    (vpic_make_id) = 464 // Lincoln
  ];

  // Lotus.
  LOTUS = 58 [
    (conglomerate) = ZHEJIANG_GEELY_HOLDING_GROUP,
    (vpic_make_id) = 466 // Lotus
  ];

  // Buick.
  BUICK = 59 [
    (conglomerate) = GENERAL_MOTORS,
    (vpic_make_id) = 468 // Buick
  ];

  // Cadillac.
  CADILLAC = 60 [
    (conglomerate) = GENERAL_MOTORS,
    (vpic_make_id) = 469 // Cadillac
  ];

  // Holden.
  HOLDEN = 61 [(vpic_make_id) = 470 /* Holden */];

  // GMC.
  GMC = 62 [
    (conglomerate) = GENERAL_MOTORS,
    (vpic_make_id) = 472 // GMC
  ];

  // Acura.
  ACURA = 63 [
    (conglomerate) = HONDA_MOTOR_COMPANY,
    (vpic_make_id) = 475 // Acura
  ];

  // Mack.
  MACK = 64 [
    (conglomerate) = VOLVO_GROUP,
    (vpic_make_id) = 490 // Mack
  ];

  // Volvo Construction Equipment.
  VOLVO_CONSTRUCTION_EQUIPMENT = 65 [(conglomerate) = VOLVO_GROUP];

  // Harley-Davidson.
  HARLEY_DAVIDSON = 66 [(vpic_make_id) = 3888 /* Harley-Davidson */];

  // Yamaha.
  YAMAHA = 67 [(vpic_make_id) = 564 /* Yamaha */];

  // Kawasaki.
  KAWASAKI = 68 [(vpic_make_id) = 510 /* Kawasaki */];

  // Ducati.
  DUCATI = 69 [
    (conglomerate) = VOLKSWAGEN_GROUP,
    (vpic_make_id) = 568 // Ducati
  ];

  // KTM.
  KTM = 70 [(vpic_make_id) = 596 /* KTM */];

  // Triumph.
  TRIUMPH = 71 [(vpic_make_id) = 565 /* Triumph */];

  // Daihatsu.
  DAIHATSU = 72 [
    (conglomerate) = TOYOTA_GROUP,
    (vpic_make_id) = 847 // Daihatsu
  ];

  // Saab.
  SAAB = 73 [(vpic_make_id) = 572 /* SAAB */];

  // Rover.
  ROVER = 74 [
    (conglomerate) = JAGUAR_LAND_ROVER_GROUP,
    (vpic_make_id) = 10652 // Rover
  ];

  // MG.
  MG = 76;

  // Stema.
  STEMA = 77;

  // Humbaur.
  HUMBAUR = 78;

  // Boeckmann.
  BOECKMANN = 79 [(vpic_make_id) = 8539 /* Bockmann Fahrzeugwerke GmbH */];

  // Mitsubishi Fuso.
  MITSUBISHI_FUSO = 81 [(vpic_make_id) = 528 /* Mitsubishi Fuso */];

  // Isuzu.
  ISUZU = 82 [(vpic_make_id) = 542 /* Isuzu */];

  // Maxus.
  MAXUS = 83;

  // Renault Trucks.
  RENAULT_TRUCKS = 84 [(conglomerate) = VOLVO_GROUP];

  // Scania.
  SCANIA = 85 [(vpic_make_id) = 5107 /* Scania */];

  // DAF.
  DAF = 86;

  // John Deere.
  JOHN_DEERE = 87 [(vpic_make_id) = 5431 /* John Deere */];

  // JYKI.
  JYKI = 88;

  // Närko.
  NARKO = 89;

  // Sisu.
  SISU = 90;

  // Volvo Buses.
  VOLVO_BUSES = 91 [(conglomerate) = VOLVO_GROUP];

  // Piako.
  PIAKO = 92;

  // Ekeri.
  EKERI = 93;

  // Schmitz Cargobull.
  SCHMITZ_CARGOBULL = 94;
}
