edition = "2023";

package wayplatform.connect.vin.v1;

import "google/protobuf/descriptor.proto";
import "wayplatform/connect/vin/v1/vpic.proto";

extend google.protobuf.EnumValueOptions {
  // The category for the enum value.
  Category category = 50347;
}

// Category of a VIN.
enum Category {
  // Default value. This value is unused.
  CATEGORY_UNSPECIFIED = 0;

  // Passenger car.
  PASSENGER_CAR = 1 [(vpic_vehicle_type_id) = 2];

  // Light commercial vehicle.
  // A commercial vehicle that weighs under 3.5 tonnes (gross vehicle weight, or GVW)
  LIGHT_COMMERCIAL_VEHICLE = 2;

  // Heavy goods vehicle.
  // Any commercial vehicle with a gross weight of over 3.5 tonnes.
  HEAVY_GOODS_VEHICLE = 3;

  // Special purpose vehicle.
  // A motor vehicle or trailer, other than an agricultural vehicle or a tow truck, built for a purpose other than carrying goods such as a mobile crane, a concrete pump or drill rig.
  SPECIAL_PURPOSE_VEHICLE = 4;

  // Trailer.
  TRAILER = 5 [(vpic_vehicle_type_id) = 6];

  // Motorcycle.
  MOTORCYCLE = 6 [(vpic_vehicle_type_id) = 1];

  // Bus.
  BUS = 7 [(vpic_vehicle_type_id) = 5];

  // Multipurpose passenger vehicle (MPV).
  MULTIPURPOSE_PASSENGER_VEHICLE = 8 [(vpic_vehicle_type_id) = 7];

  // Incomplete vehicle.
  INCOMPLETE_VEHICLE = 9 [(vpic_vehicle_type_id) = 10];

  // Off-road vehicle.
  OFF_ROAD_VEHICLE = 10 [(vpic_vehicle_type_id) = 13];

  // A truck.
  TRUCK = 11 [(vpic_vehicle_type_id) = 3];

  // Low speed vehicle (LSV).
  LOW_SPEED_VEHICLE = 12 [(vpic_vehicle_type_id) = 9];
}
