edition = "2023";

package wayplatform.connect.vin.v1;

import "wayplatform/connect/vin/v1/brand.proto";
import "wayplatform/connect/vin/v1/fuel_type.proto";
import "wayplatform/connect/vin/v1/model.proto";
import "wayplatform/connect/vin/v1/vehicle_type.proto";

// A vehicle.
message Vehicle {
  // The vehicle's brand.
  Brand brand = 1;

  // The vehicle's type.
  VehicleType type = 2;

  // The vehicle's model.
  Model model = 3;

  // The vehicle's year.
  int32 year = 4;

  // The vehicle's fuel types.
  repeated FuelType fuel_types = 5;

  // The vehicle's axle count.
  int32 axle_count = 6;
}
