edition = "2023";

package wayplatform.connect.vin.v1;

import "google/protobuf/descriptor.proto";

extend google.protobuf.EnumValueOptions {
  // The vPIC make ID for the enum value.
  repeated int32 vpic_make_id = 50384;

  // The vPIC country ID for the enum value.
  repeated int32 vpic_country_id = 50355;

  // The vPIC vehicle type ID for the enum value.
  repeated int32 vpic_vehicle_type_id = 50356;

  // The vPIC model ID for the enum value.
  repeated int32 vpic_model_id = 50357;

  // The vPIC fuel type ID for the enum value.
  repeated int32 vpic_fuel_type_id = 53428;
}
